name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: JulienKode/team-labeler-action@v0.1.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
